# Generated by Django 5.2.1 on 2026-05-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
