# Generated by Django 5.2.1 on 2026-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genero_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='ingressos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
    ]
