# Generated by Django 5.2.1 on 2026-05-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filme_criado_em_alter_filme_disponivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='ativa',
        ),
    ]
